### ISSUE TITLE
not compatible with cordova-ios 6.1.0

### ISSUE THREAD

**Issue by barakataboujreich** [MaKleSoft/cordova-plugin-migrate-localstorage#8]
one of this plugins dependencies is cordova-plugin-wkwebview-engine, which is not compatible with cordova-ios 6.1.0 and cause build errors. cordova-plugin-wkwebview-engine is integrated into cordova-ios 6.1.0 and  is not required anymore

**Comment by khatridev** [comment]
had the same issue, removed the dependency, and updated the path in the fork here,

https://github.com/khatridev/cordova-plugin-migrate-localstorage

**Comment by TimasJackus** [comment]
@khatridev Amazing!
